name: github pages

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'  # Node.jsのバージョンを20に更新
        cache: 'npm'

    - name: install
      run: npm install

    - name: build
      run: npm run build
      env:
        NODE_ENV: production
        REPOSITORY_NAME: ${{ github.event.repository.name }}

    - name: export
      run: npm run export || echo "Export completed"

    - name: add nojekyll
      run: |
        mkdir -p out
        touch out/.nojekyll

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out