name: github pages

on:
  push:
    branches:
    - main
  # 手動実行オプション追加
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest  # 最新バージョンに変更
    # 権限を明示的に設定
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3  # 新しいバージョン

    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'  # 新しいバージョン
        cache: 'npm'

    - name: install
      run: npm install

    - name: build
      run: npm run build
      env:
        NODE_ENV: production
        REPOSITORY_NAME: ${{ github.repository_name }}

    - name: export
      run: npm run export || echo "Export completed"

    - name: add nojekyll
      run: |
        mkdir -p out
        touch out/.nojekyll

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out